# Generated by Django 6.0.3 on 2026-04-27 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_course_options_and_more'),
        ('enrollments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningLog',
            fields=[
                ('log_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('event_type', models.CharField(help_text='play, pause, complete 등', max_length=50)),
                ('position_seconds', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enrollments.enrollment')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.coursesession')),
            ],
            options={
                'db_table': 'learning_logs',
            },
        ),
        migrations.CreateModel(
            name='LearningProgress',
            fields=[
                ('progress_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('progress_rate', models.DecimalField(decimal_places=2, default=0.0, help_text='진도율 (0~100)', max_digits=5)),
                ('last_position', models.IntegerField(default=0, help_text='마지막 시청 위치(초 단위)')),
                ('is_completed', models.BooleanField(default=False)),
                ('last_accessed_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresses', to='enrollments.enrollment')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresses', to='courses.coursesession')),
            ],
            options={
                'db_table': 'learning_progress',
                'unique_together': {('enrollment', 'session')},
            },
        ),
    ]
