# Generated by Django 6.0.3 on 2026-04-16 04:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_last_activity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('admin_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('institution_id', models.BigIntegerField(db_index=True)),
                ('admin_type', models.CharField(choices=[('super_admin', '최고 관리자'), ('upper_admin', '상위 관리자'), ('lower_admin', '하위 관리자')], db_index=True, max_length=20)),
                ('permissions', models.JSONField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allowed_ips', models.CharField(blank=True, help_text='접속 허용 IP 목록(콤마로 구분, 비어있으면 모두 허용)', max_length=255, null=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='admin_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Administrator',
                'verbose_name_plural': 'Administrators',
                'db_table': 'administrators',
            },
        ),
    ]
