# Generated by Django 6.0.3 on 2026-04-17 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_administrator'),
        ('institutions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrator',
            name='institution_id',
        ),
        migrations.AddField(
            model_name='administrator',
            name='institution',
            field=models.ForeignKey(blank=True, db_column='institution_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='administrators', to='institutions.institution'),
        ),
    ]
