# Generated by Django 6.0.3 on 2026-04-17 14:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('institution_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('institution_name', models.CharField(max_length=200)),
                ('ceo_name', models.CharField(blank=True, help_text='대표자 성명', max_length=50, null=True)),
                ('institution_code', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('registration_number', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('address_detail', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('fax', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('institution_type', models.CharField(choices=[('central', '중앙'), ('provincial', '도/광역시'), ('district', '시/군/구'), ('facility', '시설')], max_length=20)),
                ('region', models.CharField(blank=True, max_length=20, null=True)),
                ('zipcode', models.CharField(blank=True, max_length=10, null=True)),
                ('status', models.CharField(choices=[('active', '활성'), ('suspended', '정지'), ('deleted', '삭제')], default='active', max_length=20)),
                ('employee_count', models.IntegerField(default=0)),
                ('allowed_ips', models.CharField(blank=True, max_length=255, null=True)),
                ('biz_license_file_path', models.CharField(blank=True, max_length=255, null=True)),
                ('logo_file_path', models.CharField(blank=True, max_length=255, null=True)),
                ('staff_file_path', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent_institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_institutions', to='institutions.institution')),
            ],
            options={
                'verbose_name': 'Institution',
                'verbose_name_plural': 'Institutions',
                'db_table': 'institutions',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('employee_number', models.CharField(blank=True, max_length=50, null=True)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('hire_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_profiles', to=settings.AUTH_USER_MODEL)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='institutions.institution')),
            ],
            options={
                'db_table': 'employees',
            },
        ),
        migrations.CreateModel(
            name='InstitutionApplication',
            fields=[
                ('application_id', models.BigAutoField(help_text='신청 고유 번호', primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', '대기중'), ('approved', '승인됨'), ('rejected', '반려됨')], default='pending', help_text='처리 상태', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, help_text='반려 사유', null=True)),
                ('processed_at', models.DateTimeField(blank=True, help_text='처리 일시', null=True)),
                ('processed_by', models.BigIntegerField(blank=True, help_text='처리한 관리자 ID', null=True)),
                ('institution_name', models.CharField(help_text='기관명', max_length=200)),
                ('registration_number', models.CharField(help_text='사업자등록번호', max_length=50)),
                ('ceo_name', models.CharField(help_text='대표자 성명', max_length=50)),
                ('institution_type', models.CharField(choices=[('central', '중앙'), ('provincial', '도/광역시'), ('district', '시/군/구'), ('facility', '시설')], help_text='기관 유형', max_length=20)),
                ('region', models.CharField(help_text='지역', max_length=20)),
                ('zipcode', models.CharField(help_text='우편번호', max_length=10)),
                ('address', models.CharField(help_text='주소', max_length=255)),
                ('address_detail', models.CharField(blank=True, help_text='상세주소', max_length=255, null=True)),
                ('phone', models.CharField(help_text='대표 전화번호', max_length=20)),
                ('fax', models.CharField(blank=True, help_text='대표 팩스', max_length=20, null=True)),
                ('email', models.EmailField(help_text='대표 이메일', max_length=100)),
                ('employee_count', models.IntegerField(default=0, help_text='직원 수')),
                ('allowed_ips', models.CharField(blank=True, help_text='접속 허용 IP 목록', max_length=255, null=True)),
                ('biz_license_file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('biz_license_file_path', models.CharField(blank=True, max_length=255, null=True)),
                ('logo_file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('logo_file_path', models.CharField(blank=True, max_length=255, null=True)),
                ('staff_file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('staff_file_path', models.CharField(blank=True, max_length=255, null=True)),
                ('mgr_name', models.CharField(help_text='담당자 성명', max_length=50)),
                ('mgr_dept', models.CharField(blank=True, help_text='담당자 부서', max_length=50, null=True)),
                ('mgr_position', models.CharField(blank=True, help_text='직급', max_length=50, null=True)),
                ('mgr_phone', models.CharField(help_text='휴대폰 번호', max_length=20)),
                ('mgr_email', models.EmailField(help_text='담당자 이메일', max_length=100)),
                ('is_privacy_policy_agreed', models.BooleanField(default=False)),
                ('emp_proof_file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('emp_proof_file_path', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='신청자 ID', on_delete=django.db.models.deletion.CASCADE, related_name='institution_apps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'institution_applications',
            },
        ),
        migrations.CreateModel(
            name='UserInstitution',
            fields=[
                ('user_institution_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('position', models.CharField(blank=True, max_length=100, null=True)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_mappings', to='institutions.institution')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='institution_mappings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_institutions',
            },
        ),
    ]
