# Generated by Django 6.0.3 on 2026-03-10 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('course_code', models.CharField(max_length=50, unique=True)),
                ('course_name', models.CharField(max_length=255)),
                ('course_type', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('package', 'Package')], max_length=20)),
                ('category_id', models.BigIntegerField(blank=True, null=True)),
                ('education_area', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.CharField(max_length=100)),
                ('sub_category', models.CharField(blank=True, max_length=100, null=True)),
                ('edu_classification', models.CharField(blank=True, max_length=50, null=True)),
                ('client_code', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('education_goal', models.TextField(blank=True, null=True)),
                ('curriculum_summary', models.TextField(blank=True, null=True)),
                ('target_audience', models.CharField(blank=True, max_length=255, null=True)),
                ('education_location', models.CharField(blank=True, max_length=255, null=True)),
                ('education_time', models.CharField(blank=True, max_length=100, null=True)),
                ('launch_time', models.CharField(blank=True, max_length=100, null=True)),
                ('launch_provided', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1)),
                ('accommodation_provided', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1)),
                ('stay_days', models.IntegerField(default=0)),
                ('accommodation_period', models.CharField(blank=True, max_length=100, null=True)),
                ('duration_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('learning_days', models.IntegerField(default=0)),
                ('access_period_days', models.IntegerField(default=30)),
                ('total_sessions', models.IntegerField(blank=True, null=True)),
                ('max_students', models.IntegerField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('discount_rate', models.IntegerField(default=0)),
                ('completion_rate', models.IntegerField(default=90)),
                ('is_free', models.BooleanField(default=False)),
                ('is_approval_required', models.BooleanField(default=False)),
                ('remark', models.TextField(blank=True, null=True)),
                ('thumbnail_image', models.CharField(blank=True, max_length=255, null=True)),
                ('video_url', models.CharField(blank=True, max_length=500, null=True)),
                ('view_count', models.IntegerField(default=0)),
                ('course_status', models.CharField(choices=[('published', 'Published'), ('private', 'Private'), ('draft', 'Draft'), ('deleted', 'Deleted')], default='draft', max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('application_start_date', models.DateField(blank=True, null=True)),
                ('application_end_date', models.DateField(blank=True, null=True)),
                ('institution_id', models.BigIntegerField(blank=True, null=True)),
                ('pre_survey_id', models.BigIntegerField(blank=True, null=True)),
                ('post_survey_id', models.BigIntegerField(blank=True, null=True)),
                ('satisfaction_survey_id', models.BigIntegerField(blank=True, null=True)),
                ('created_by', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('access_type', models.CharField(choices=[('period', 'Period'), ('days', 'Days')], default='days', max_length=20)),
                ('retake_discount_rate', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'courses',
                'ordering': ['-created_at'],
            },
        ),
    ]
