# Generated by Django 6.0.3 on 2026-04-22 05:41

import courses.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('institutions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['created_at']},
        ),
        migrations.RenameField(
            model_name='course',
            old_name='launch_provided',
            new_name='lunch_provided',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='launch_time',
            new_name='lunch_time',
        ),
        migrations.RemoveField(
            model_name='course',
            name='institution_id',
        ),
        migrations.AddField(
            model_name='course',
            name='institution',
            field=models.ForeignKey(blank=True, db_column='institution_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='institutions.institution'),
        ),
        migrations.AlterField(
            model_name='course',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='created_courses', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='thumbnail_image',
            field=models.ImageField(blank=True, null=True, upload_to=courses.models.course_thumbnail_upload_path),
        ),
        migrations.CreateModel(
            name='CourseCurriculum',
            fields=[
                ('curriculum_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('chapter_name', models.CharField(help_text='목차명/주제', max_length=255)),
                ('description', models.TextField(blank=True, help_text='상세 내용', null=True)),
                ('instructor_name', models.CharField(blank=True, help_text='담당 강사명(옵션)', max_length=100, null=True)),
                ('running_time', models.IntegerField(blank=True, help_text='소요시간(분)', null=True)),
                ('display_order', models.IntegerField(default=0, help_text='표시 순서')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculums', to='courses.course')),
            ],
            options={
                'db_table': 'course_curriculums',
                'ordering': ['display_order', 'curriculum_id'],
            },
        ),
        migrations.CreateModel(
            name='CourseMaterial',
            fields=[
                ('material_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('material_type', models.CharField(choices=[('syllabus', '강의계획서'), ('handout', '유인물'), ('document', '문서'), ('video', '영상'), ('etc', '기타')], max_length=20)),
                ('material_name', models.CharField(max_length=255)),
                ('file_path', models.CharField(blank=True, max_length=500, null=True)),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='courses.course')),
            ],
            options={
                'db_table': 'course_materials',
            },
        ),
        migrations.CreateModel(
            name='CourseReview',
            fields=[
                ('review_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('rating', models.IntegerField(default=5, help_text='별점(1~5)')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='courses.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'course_reviews',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CourseSession',
            fields=[
                ('session_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('session_number', models.IntegerField(db_index=True)),
                ('session_name', models.CharField(max_length=255)),
                ('session_description', models.TextField(blank=True, null=True)),
                ('video_url', models.CharField(blank=True, max_length=500, null=True)),
                ('duration_minutes', models.IntegerField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(default=0)),
                ('materials', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='courses.course')),
            ],
            options={
                'db_table': 'course_sessions',
                'ordering': ['session_number'],
            },
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('instructor_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('affiliation', models.CharField(blank=True, help_text='소속(협의회 등)', max_length=100, null=True)),
                ('affiliation_detail', models.CharField(blank=True, help_text='소속 상세 직접입력', max_length=255, null=True)),
                ('bio', models.TextField(blank=True, help_text='자기소개/셀프어필', null=True)),
                ('specialization', models.CharField(blank=True, help_text='전공 분야', max_length=255, null=True)),
                ('experience_years', models.IntegerField(blank=True, help_text='경력 연수', null=True)),
                ('certification', models.CharField(blank=True, help_text='보유 자격증 텍스트', max_length=255, null=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to=courses.models.instructor_profile_upload_path)),
                ('region', models.CharField(blank=True, help_text='강의 가능 지역', max_length=255, null=True)),
                ('agreed_marketing', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution', models.ForeignKey(blank=True, db_column='institution_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instructors', to='institutions.institution')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='instructor_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'instructors',
            },
        ),
        migrations.CreateModel(
            name='InstructorAttachment',
            fields=[
                ('attachment_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('file_type', models.CharField(help_text='문서 종류(certificate, profile_pdf 등)', max_length=50)),
                ('file_path', models.FileField(upload_to=courses.models.instructor_attachment_upload_path)),
                ('original_name', models.CharField(max_length=255)),
                ('file_size', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='courses.instructor')),
            ],
            options={
                'db_table': 'instructor_attachments',
            },
        ),
        migrations.CreateModel(
            name='CoursePackageItem',
            fields=[
                ('package_item_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sort_order', models.IntegerField(default=0, help_text='패키지 내 강의 노출 순서')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(help_text='포함된(하위) 강좌', on_delete=django.db.models.deletion.CASCADE, related_name='package_parents', to='courses.course')),
                ('package', models.ForeignKey(help_text='패키지(상위) 강좌', on_delete=django.db.models.deletion.CASCADE, related_name='child_courses', to='courses.course')),
            ],
            options={
                'db_table': 'course_package_items',
                'ordering': ['sort_order'],
                'unique_together': {('package', 'course')},
            },
        ),
        migrations.CreateModel(
            name='CourseStatistic',
            fields=[
                ('stat_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('stat_date', models.DateField(db_index=True)),
                ('total_enrollments', models.IntegerField(default=0)),
                ('completed_enrollments', models.IntegerField(default=0)),
                ('average_progress', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='courses.course')),
            ],
            options={
                'db_table': 'course_statistics',
                'ordering': ['-stat_date'],
                'unique_together': {('course', 'stat_date')},
            },
        ),
        migrations.CreateModel(
            name='CourseInstructor',
            fields=[
                ('course_instructor_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('is_primary', models.BooleanField(default=False, help_text='대표/메인 강사 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_instructors', to='courses.course')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_mappings', to='courses.instructor')),
            ],
            options={
                'db_table': 'course_instructors',
                'unique_together': {('course', 'instructor')},
            },
        ),
    ]
